# https://ndb796.tistory.com/96

FROM ubuntu:18.04

# ENV DEBIAN_FRONTEND noninteractive

RUN cd /etc/apt && \
    sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' sources.list && \
    apt-get update && \
    apt-get install -y build-essential python-dev cmake wget git git-lfs vim

# RUN apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
#     && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
# ENV LANG en_US.utf8

# https://snowdeer.github.io/linux/2018/04/10/upgrade-cmake/
# RUN wget -c https://github.com/Kitware/CMake/releases/download/v3.18.0/cmake-3.18.0.tar.gz && \
COPY cmake-3.18.0.tar.gz /cmake-3.18.0.tar.gz
RUN tar -zxvf cmake-3.18.0.tar.gz && \
    cd /cmake-3.18.0 && \
    cmake -DCMAKE_USE_OPENSSL=OFF . && \
    make && \
    make install
# RUN echo "export PATH=$PATH:/cmake-3.18.0/bin" >> ~/.bashrc && \
#     source ~/.bashrc

# WORKDIR /

# RUN git clone https://github.com/llvm/llvm-project.git
# RUN cd /llvm-project && \
#     mkdir build
    
# WORKDIR /llvm-project/build

# RUN cmake -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm

# RUN make clang

# RUN echo "export PATH=$PATH:/llvm-project/build/bin" >> ~/.profile && \
#     source ~/.profile

# RUN clang --version

# RUN make check-clang

CMD [ "/bin/bash" ]